// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsHSOJABsqZPzUKs0v3AqdIBB2piUSymU',
    appId: '1:640941934000:android:4ddc7444789c3b0bfd0275',
    messagingSenderId: '640941934000',
    projectId: 'momo-app-831e5',
    storageBucket: 'momo-app-831e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTxhu8W1dBGFKoQKqui9RuvSwmooGqasY',
    appId: '1:640941934000:ios:df1cff551613c1b8fd0275',
    messagingSenderId: '640941934000',
    projectId: 'momo-app-831e5',
    storageBucket: 'momo-app-831e5.firebasestorage.app',
    iosClientId: '640941934000-cet5m2n4nmj733ar9nt90vh0r3p3io7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.ClassMate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASwWZDNPM0erhDN4WDzcfTmtpOMuRFxuE',
    appId: '1:640941934000:web:3491001487c331e2fd0275',
    messagingSenderId: '640941934000',
    projectId: 'momo-app-831e5',
    authDomain: 'momo-app-831e5.firebaseapp.com',
    storageBucket: 'momo-app-831e5.firebasestorage.app',
    measurementId: 'G-RMTKZ3K30B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTxhu8W1dBGFKoQKqui9RuvSwmooGqasY',
    appId: '1:640941934000:ios:df1cff551613c1b8fd0275',
    messagingSenderId: '640941934000',
    projectId: 'momo-app-831e5',
    storageBucket: 'momo-app-831e5.firebasestorage.app',
    iosClientId: '640941934000-cet5m2n4nmj733ar9nt90vh0r3p3io7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.ClassMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASwWZDNPM0erhDN4WDzcfTmtpOMuRFxuE',
    appId: '1:640941934000:web:df64564916e8f297fd0275',
    messagingSenderId: '640941934000',
    projectId: 'momo-app-831e5',
    authDomain: 'momo-app-831e5.firebaseapp.com',
    storageBucket: 'momo-app-831e5.firebasestorage.app',
    measurementId: 'G-4GGQ2J30Z7',
  );

}